title: melonmochi
description: A website with a blog
footer_text: Copyright 2021 Holly Doogood
header_feature_image: ../uploads/pages.jpg
header_text: melonmochi
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
